apiVersion: integration/v1
kind: Trigger
name: jira-trigger-issue-deleted
version: 1
summary: Jira issue deleted
description: |
  This trigger fires when a Jira issue is deleted.

responders:
- webhook

schemas:
  spec:
    $schema: http://json-schema.org/draft-07/schema#

build:
  apiVersion: build/v1
  kind: Docker

publish:
  repository: relaysh/jira-trigger-issue-deleted
