apiVersion: integration/v1
kind: Trigger
name: jira-trigger-issue-created
version: 1
summary: Jira issue created
description: |
  This trigger fires when a Jira issue is created.

responders:
- webhook

schemas:
  spec:
    $schema: http://json-schema.org/draft-07/schema#

build:
  apiVersion: build/v1
  kind: Docker
